baseURL = 'https://uscterzosettore.it'
languageCode = 'it-IT'
title = 'USC Ente del Terzo Settore'
theme = 'usc-professional'

# Content settings
defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = false
hasCJKLanguage = false
enableEmoji = true
enableGitInfo = true

# TIMEZONE E DATE - AGGIUNTO
timeZone = 'Europe/Rome'

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats
enableRobotsTXT = true
canonifyURLs = false
relativeURLs = false

# Pagination
[pagination]
  pagerSize = 10
  path = "pagina"

# Taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Permalinks
[permalinks]
  posts = '/posts/:year/:month/:slug/'
  categories = '/categories/:slug/'

# CONFIGURAZIONE LINGUA ITALIANA - AGGIUNTO
[languages]
  [languages.it]
    languageCode = 'it-IT'
    languageName = 'Italiano'
    weight = 1
    title = 'USC Ente del Terzo Settore'
    
    [languages.it.params]
      description = 'Blog ufficiale USC Ente del Terzo Settore - Notizie, approfondimenti e risorse dal mondo del terzo settore italiano'
      
    # Date format personalizzati per l'italiano
    [languages.it.dates]
      month_names = ["gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre"]
      month_names_short = ["gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic"]
      day_names = ["domenica", "lunedì", "martedì", "mercoledì", "giovedì", "venerdì", "sabato"]
      day_names_short = ["dom", "lun", "mar", "mer", "gio", "ven", "sab"]

# Site parameters
[params]
  description = 'Blog ufficiale USC Ente del Terzo Settore - Notizie, approfondimenti e risorse dal mondo del terzo settore italiano'
  author = 'USC Ente del Terzo Settore'
  
  # Contact info
  email = 'redazione@uscterzosettore.it'
  phone = '+39 06 0000 0000'
  address = 'Via del Castro Pretorio, 30, 00185 Roma, Italia'
  
  # Social media
  linkedin = 'https://linkedin.com/company/usc-terzo-settore'
  
  # Newsletter
  newsletter_signup = true
  convertkit_form_uid = ''
  
  # Analytics
  google_analytics = 'G-7XY2JTE4PN'
  
  # Features
  show_reading_time = true
  show_share_buttons = true
  show_related_posts = true

  [params.analytics]
    google_analytics_4 = true
    anonymize_ip = true
    disable_advertising = true  
    disable_demographics = true
    cookie_consent_required = true
  
  # SEO
  [params.seo]
    meta_description_length = 160
    meta_og_image = '/images/usc-og-image.jpg'

# Menu configuration
[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
    
  [[menu.main]]
    identifier = 'categories'
    name = 'Categorie'
    url = '/categories/'
    weight = 20
    
  [[menu.main]]
    identifier = 'chi-siamo'
    name = 'Chi Siamo'
    url = '/chi-siamo/'
    weight = 30

  # Footer menu
  [[menu.footer]]
    name = 'Privacy Policy'
    url = '/privacy/'
    weight = 10
    
  [[menu.footer]]
    name = 'Contatti'
    url = '/contatti/'
    weight = 20

  [[menu.footer]]
    name = 'Cookie Policy'  
    url = '/cookie-policy/'
    weight = 15

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'github'
    tabWidth = 2
    
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Image processing
[imaging]
  resampleFilter = 'CatmullRom'
  quality = 85
  anchor = 'smart'

# Minification
[minify]
  disableXML = true
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = true
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 2
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 2

# Output formats
[outputs]
  home = ['HTML', 'RSS', 'JSON']
  page = ['HTML']
  section = ['HTML', 'RSS']
  taxonomy = ['HTML', 'RSS']
  term = ['HTML', 'RSS']

# RSS configuration
[services]
  [services.rss]
    limit = 20

# Security
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^git$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

# Module configuration
[module]
  [module.hugoVersion]
    extended = false
    min = '0.112.0'

# Sostituisci la sezione [params.all_categories] nel tuo hugo.toml con questa:

# Configurazione categorie - SINTASSI TOML CORRETTA
[[params.all_categories.list]]
name = "Agricoltura Sociale"
image = "/images/categories/agricoltura-sociale.jpg"
description = "Progetti e iniziative che uniscono agricoltura e inclusione sociale"

[[params.all_categories.list]]
name = "Assistenza Sanitaria"
image = "/images/categories/assistenza-sanitaria.jpg"
description = "Supporto sanitario e servizi per il benessere della comunità"

# Questa categoria non è più necessaria, ma dovra diventare una sezione fine a se stessa nella barra di navigazione
# [[params.all_categories.list]]
# name = "Donazioni"
# image = "/images/categories/donazioni.jpg"
# description = "Iniziative di raccolta fondi e supporto alla comunità"

[[params.all_categories.list]]
name = "Giovani Idee"
image = "/images/categories/giovani-idee.jpg"
description = "Progetti innovativi e iniziative dei giovani per la comunità"

[[params.all_categories.list]]
name = "News"
image = "/images/categories/news.jpg"
description = "Ultime notizie e aggiornamenti dal mondo del terzo settore"

[[params.all_categories.list]]
name = "Patronato"
image = "/images/categories/patronato.jpg"
description = "Servizi di patronato e assistenza per pratiche burocratiche"

[[params.all_categories.list]]
name = "Tutela Legale"
image = "/images/categories/tutela-legale.jpg"
description = "Supporto legale e consulenza per diritti e normative"