baseURL = 'https://uscterzosettore.it'
languageCode = 'it-it'
title = 'USC Ente del Terzo Settore'
theme = 'usc-professional'

# Content settings
defaultContentLanguage = 'it'
hasCJKLanguage = false
enableEmoji = true
enableGitInfo = true

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats
enableRobotsTXT = true
canonifyURLs = false
relativeURLs = false

# Pagination
[pagination]
  pagerSize = 10
  path = "pagina"

# Taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Permalinks
[permalinks]
  posts = '/posts/:year/:month/:slug/'
  categories = '/categories/:slug/'

# Site parameters
[params]
  description = 'Blog ufficiale USC Ente del Terzo Settore - Notizie, approfondimenti e risorse dal mondo del terzo settore italiano'
  author = 'USC Ente del Terzo Settore'
  
  # Contact info
  email = 'info@uscterzosettore.it'
  phone = '+39 06 0000 0000'
  address = 'Via del Castro Pretorio, 30, 00185 Roma, Italia'
  
  # Social media
  linkedin = 'https://linkedin.com/company/usc-terzo-settore'
  
  # Newsletter
  newsletter_signup = true
  convertkit_form_uid = '' # Da configurare con ConvertKit
  
  # Analytics
  google_analytics = '' # Da configurare con Google Analytics
  
  # Features
  show_reading_time = true
  show_share_buttons = true
  show_related_posts = true
  
  # SEO
  [params.seo]
    meta_description_length = 160
    meta_og_image = '/images/usc-og-image.jpg'

# Menu configuration
[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
    
  [[menu.main]]
    identifier = 'categories'
    name = 'Categorie'
    url = '/categories/'
    weight = 20
    
  [[menu.main]]
    identifier = 'chi-siamo'
    name = 'Chi Siamo'
    url = '/chi-siamo/'
    weight = 30

  # Footer menu
  [[menu.footer]]
    name = 'Privacy Policy'
    url = '/privacy/'
    weight = 10
    
  [[menu.footer]]
    name = 'Contatti'
    url = '/contatti/'
    weight = 20

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'github'
    tabWidth = 2
    
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Image processing
[imaging]
  resampleFilter = 'CatmullRom'
  quality = 85
  anchor = 'smart'

# Minification
[minify]
  disableXML = true
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = true
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 2
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 2

# Output formats
[outputs]
  home = ['HTML', 'RSS', 'JSON']
  page = ['HTML']
  section = ['HTML', 'RSS']
  taxonomy = ['HTML', 'RSS']
  term = ['HTML', 'RSS']

# RSS configuration
[services]
  [services.rss]
    limit = 20

# Security
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^git$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

# Module configuration (if using Hugo modules)
[module]
  [module.hugoVersion]
    extended = false
    min = '0.112.0'