baseURL = 'https://uscterzosettore.it'
languageCode = 'it-it'
title = 'USC Ente del Terzo Settore'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "USC Ente del Terzo Settore"
  description = "Notizie, insights e aggiornamenti dal mondo del terzo settore"
  keywords = ["terzo settore", "no-profit", "volontariato"]
  author = "USC Team"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

  [params.homeInfoParams]
    Title = "USC Ente del Terzo Settore"
    Content = "Benvenuti nel nostro blog dedicato al mondo del terzo settore. Qui troverete notizie, approfondimenti e risorse per il non-profit."

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/company/usc-terzo-settore"

[[params.socialIcons]]
  name = "email"
  url = "mailto:info@uscterzosettore.it"

[params.editPost]
  URL = "https://github.com/yourusername/uscterzosettore-blog/tree/main/content"
  Text = "Suggerisci modifiche"
  appendFilePath = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "posts"
  name = "Articoli"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "Chi Siamo"
  url = "/about/"
  weight = 30

[[menu.main]]
  identifier = "contact"
  name = "Contatti"
  url = "/contact/"
  weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'github'

[outputs]
  home = ["HTML", "RSS", "JSON"]