backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://uscterzosettore.it
display_url: https://uscterzosettore.it
logo_url: /images/logo-usc.png

show_preview_links: true
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "📝 Articoli Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    
    fields:
      - label: "Titolo"
        name: "title"
        widget: "string"
        
      - label: "Data Pubblicazione"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss+02:00"
        
      - label: "Categoria"
        name: "categories"
        widget: "select"
        multiple: false
        options:
          - "Agricoltura Sociale"
          - "Tutela Legale"
          - "Assistenza Sanitaria"
          - "Patronato"
          - "Giovani Idee"
          - "Donazioni"
          - "News"
        default: []
        
      - label: "Immagine Copertina"
        name: "cover"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - label: "Immagine"
            name: "image"
            widget: "image"
            required: false
          - label: "Alt text"
            name: "alt"
            widget: "string"
            required: false
            
      - label: "Descrizione"
        name: "description"
        widget: "text"
        required: false
        
      - label: "Autore"
        name: "author"
        widget: "string"
        default: "Redazione USC"
        
      - label: "Contenuto"
        name: "body"
        widget: "markdown"
