backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articoli Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "category", widget: "select", 
         options: ["Agricoltura Sociale", "Tutela Legale", "Assistenza Sanitaria", 
                  "Patronato", "Giovani Idee", "Donazioni", "News"]}
      - {label: "Immagine Copertina", name: "featured_image", widget: "image", required: false}
      - {label: "Riassunto", name: "excerpt", widget: "text", required: false}
      - {label: "Autore", name: "author", widget: "string", default: "Redazione USC"}
      - {label: "Bozza", name: "draft", widget: "boolean", default: false}
      - {label: "Contenuto", name: "body", widget: "markdown"}
      
  - name: "pages"
    label: "Pagine"
    files:
      - label: "Chi Siamo"
        name: "about"
        file: "content/chi-siamo/_index.md"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Contenuto", name: "body", widget: "markdown"}